### ISSUE TITLE
FE ArgumentCountError SpreadsheetProcessor::__construct(), 0 passed and  exactly 3 expected

### ISSUE THREAD

**Issue by mcsikos-udg** [hoogi91/spreadsheets#39] opened 2021-07-02 13:34 UTC
Hi hoogie91, vte-udg asked me to contact you about an update problem.

We have updated spreadsheets from 1.1.2 to 2.0.2 in a TYPO3 10.4.17. We are now experiencing the following problem:

**Version(s) affected**: 
2.0.2

**Description**  
ArgumentCountError Too few arguments to function Hoogi91\Spreadsheets\DataProcessing\SpreadsheetProcessor::__construct(), 0 passed and  exactly 3 expected

**How to reproduce**  
Call a FE-Page with a spreadsheed content element

**Possible Solution**  
This is one of the best problems: everything should be correct, but it still doesn't work.
The __construct() is correct, the Services.yaml is correct.
I have no idea why it's banging here.

If I replace the __construct() with the following, everything is fine:

    public function __construct() {
        /** @var ExtractorService $extractorServicel */
        $this->extractorService = GeneralUtility::makeInstance(ExtractorService::class);

        /** @var StyleService $styleService */
        $this->styleService = GeneralUtility::makeInstance(StyleService::class);

        /** @var PageRenderer $pageRenderer */
        $this->pageRenderer = GeneralUtility::makeInstance(PageRenderer::class);
    }

Btw, in "charts", the __construct() is done in the same way as my replacement, charts are working fine.

Maybe you can look at this again and find a solution for this.

Best of wishes

mcsikos

**Comment by hoogi91** [comment] 2021-07-20 20:47
Hey @mcsikos-udg,

I can't reproduce this problem on my local machine and thus I'm a bit confused what creates this error.
Could you please verify if this is related to following discussion => https://stackoverflow.com/questions/62347224/fatal-error-uncaught-argumentcounterror-too-few-arguments-to-function-typo3-cm
Please have a look on this comment => https://stackoverflow.com/a/67296888 as maybe another extension creates this error.

If you have further information please send those to me :)

**Comment by vte-udg** [comment] 2021-08-17 16:54
Hey there,
the Services.yaml of the other extensions that use them seem fine to me. We've decided to patch spreadsheets, thus used the old way of dependency injection in

spreadsheets/Classes/DataProcessing/SpreadsheetProcessor.php

public function __construct() {
        /** @var ExtractorService $extractorService */
        $this->extractorService = GeneralUtility::makeInstance(ExtractorService::class);
        /** @var StyleService $styleService */
        $this->styleService = GeneralUtility::makeInstance(StyleService::class);
        /** @var PageRenderer $pageRenderer */
        $this->pageRenderer = GeneralUtility::makeInstance(PageRenderer::class);
    }

and
spreadsheets/Classes/Service/StyleService.php

public function __construct()
    {
        /** @var ValueMappingService $mappingService */
        $this->mappingService = GeneralUtility::makeInstance(ValueMappingService::class);
    }

But feel free to close this issue if no one else is experiencing it :/

**Comment by hoogi91** [comment] 2022-01-16 20:17
Hey @vte-udg,
I now did a lot of research but I'm still not able to reproduce this issue in a common installation. Sometimes when I'm switching through multiple TYPO3 versions this issue pops up. So I would recommend here to see if this has to do with several other extensions or TYPO3 configurations from past versions. Maybe it's just because of a missing deprecation that has not been migrated or similar.

I'm not 100% sure but in my opinion this issue seems to happen if some of the TYPO3 caches is filled with data on how these classes are created. Hope this helps you by fixing your issues. If you want further help or support contact me via pn :)

**Closed by hoogi91** 2022-01-16 20:17 UTC
